[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4.3",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"] 
namespaces = true

[tool.setuptools_scm]
write_to = "src/lpf_detchar/_version.py"

[tool.setuptools.dynamic]
version = {attr = "lpf_detchar._version.__version__"}

[project]
name = "lpf_detchar"
authors = [
  { name="Rhiannon Udall", email="rhiannon.udall@ligo.org" },
]
description = "Tools for detchar investigations of LISA pathfinder data"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Gravitational Wave Scientists",
    "Development Status :: 1 - Initial Setup"
]
dynamic = ["version"]
dependencies = [
    "loguru",
    "typer",
    "pydantic",
    "pydantic_yaml",
    "jax",
    "scikit-learn",
    "h5py"
]

[project.scripts]


[project.urls]
homepage = "https://github.com/Rhiannon-Udall/python-package-template"
issues = "https://github.com/Rhiannon-Udall/python-package-template/issues"
