[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4.3",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"] 
namespaces = true

[tool.setuptools_scm]
write_to = "src/my_python_package/_version.py"

[project]
name = "my-python-package"
authors = [
  { name="Albert Einstein", email="albert.einstein@ligo.org" },
]
description = "A template for how to build your own python package, with opinionated choices for configuration"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Gravitational Wave Scientists",
    "Development Status :: 1 - Initial Setup"
]
dynamic = ["version"]
dependencies = [
    "loguru",
    "typer"
]

[project.scripts]
template_python_project_hello = "my_python_package:cli_hello"

[tool.setuptools.dynamic]
version = {attr = "my_python_package._version.__version__"}


[project.urls]
"Homepage" = "https://github.com/Rhiannon-Udall/python-package-template"
"Bug Tracker" = "https://github.com/Rhiannon-Udall/python-package-template/issues"
